---

- name: extensions > Checks already enabled extensions
  shell: "dpkg --get-selections 'php{{ manala_php_version }}-*'|grep -v deinstall|cut -f 1"
  register: __manala_php_extensions_enabled
  always_run: true
  ignore_errors: true
  changed_when: false

- name: extensions > Compute already enabled extensions
  set_fact:
    __manala_php_extensions_enabled: "{{ __manala_php_extensions_enabled.stdout_lines|difference(manala_php_extensions_exclude)|list }}"

- name: extensions > Install packages
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: false
    update_cache:       true
    cache_valid_time:   3600
  with_items: "{{ manala_php_extensions|map('regex_replace','^(.*)$','php' ~ manala_php_version ~ '-\\1')|difference(__manala_php_extensions_enabled) }}"
  notify:
    - php fpm restart

- name: extensions > Remove packages
  apt:
    name: "{{ item }}"
    state: absent
    purge: true
  with_items: "{{ __manala_php_extensions_enabled|difference(manala_php_extensions|map('regex_replace','^(.*)$','php' ~ manala_php_version ~ '-\\1')|list) }}"
  notify:
    - php fpm restart
