---

- name: install > Packages
  apt:
    name:  "{{ item }}"
    state: present
    install_recommends: false
    update_cache:       true
    cache_valid_time:   3600
  with_manala_php_install_packages:
    - "{{ manala_php_version|string }}"
    - "{{ manala_php_sapis }}"
    - "{{ manala_php_extensions }}"
