---

# Requirements
- include: requirements.yml
  tags:
    - manala_php

# Install
- include: install.yml
  tags:
    - manala_php

# Extensions
- include: extensions.yml
  tags:
    - manala_php

# Configs - Global
- include: configs_global.yml
  when: manala_php_configs_global
  tags:
    - manala_php

# Configs
- include: configs.yml
  when: not manala_php_configs_global
  with_items: "{{ manala_php_sapis }}"
  loop_control:
    loop_var: __manala_php_sapi
  tags:
    - manala_php

# # Fpm pools
# - include: fpm_pools.yml
#   when: ('fpm' in manala_php_sapis)
#   tags:
#     - manala_php
#
# # Blackfire
# - include: blackfire.yml
#   when: manala_php_blackfire
#   tags:
#     - manala_php
#
# # Services
# - include: services.yml
#   tags:
#     - manala_php
#     - manala.services
#
# # Applications
# - include: applications.yml
#   tags:
#     - manala_php
