---

- include: requirements.yml
- include: install.yml
- include: extensions.yml
- include: configs_global.yml
  when: manala_php_configs_global
- include: configs_sapi.yml
  vars:
    __manala_php_sapi: fpm
  when: (not manala_php_configs_global) and ('fpm' in manala_php_sapis)
- include: configs_sapi.yml
  vars:
    __manala_php_sapi: cli
  when: (not manala_php_configs_global) and ('cli' in manala_php_sapis)
- include: fpm_pools.yml
  when: ('fpm' in manala_php_sapis)
- include: services.yml
  tags: manala_services
- include: applications.yml
