---

# Requirements
- name: requirements
  assert:
    that:
      - manala_php_version in manala_php_versions.keys()
      - manala_php_versions[manala_php_version].release == ansible_distribution_release
    msg: |
      You must set "manala_php_version" to either {{ manala_php_versions.keys()|join(', ') }}
      depending on the following releases {{ manala_php_versions.keys()|map('extract', manala_php_versions, 'release')|join(', ') }} 
  always_run: true
  register: __manala_php_requirements_result
  tags:
    - manala_php

# Install
- include: install.yml
  tags:
    - manala_php

# Extensions
- include: extensions.yml
  tags:
    - manala_php

# Configs - Global
- include: configs_global.yml
  when: manala_php_configs_global
  tags:
    - manala_php

# Configs - Sapi Fpm
- include: configs_sapi.yml
  vars:
    __manala_php_sapi: fpm
  when: (not manala_php_configs_global) and ('fpm' in manala_php_sapis)
  tags:
    - manala_php

# Configs - Sapi Cli
- include: configs_sapi.yml
  vars:
    __manala_php_sapi: cli
  when: (not manala_php_configs_global) and ('cli' in manala_php_sapis)
  tags:
    - manala_php

# Fpm pools
- include: fpm_pools.yml
  when: ('fpm' in manala_php_sapis)
  tags:
    - manala_php

# Blackfire
- include: blackfire.yml
  when: manala_php_blackfire
  tags:
    - manala_php

# Services
- include: services.yml
  tags:
    - manala_php
    - manala.services

# Applications
- include: applications.yml
  tags:
    - manala_php
